<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ServiceManagerExamples\Module'                        => __DIR__ . '/Module.php',
    'ServiceManagerExamples\Controller\TutorialController' => __DIR__ . '/src/ServiceManagerExamples/Controller/TutorialController.php',
    'ServiceManagerExamplesTest\Framework\TestCase'        => __DIR__ . '/tests/ServiceManagerExamples/Framework/TestCase.php',
    'ServiceManagerExamplesTest\SampleTest'                => __DIR__ . '/tests/ServiceManagerExamples/SampleTest.php',
);
