<strong>Module:</strong>        ServiceManagerExamples &raquo;
<strong>Controller:</strong>    Tutorial &raquo;
<strong>Action:</strong>        index

<div>

<h3>Following the advice of a consultant, 
the magic practitioner decided to use a different strategy</h3>

<h4>The Strategy:</h4>
<?php foreach ($this->response as $response) : ?>
<?php echo $this->escapehtml($response); ?>
<?php endforeach; ?>

<h4>The Reward:</h4>
<?php echo $this->escapehtml($reward); ?>
</div>
