<div class="hero-unit">
    <h1><?=sprintf($this->translate('YAY! %sZend DB Examples%s'), '<span class="zf-green">', '</span>')?></h1>
    <p>
        <?=sprintf($this->translate('Check out the README. Follow through example by example.',
            \Zend\Version\Version::VERSION))?>
    </p>
</div>

<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('1) Service Manager') ?></h2>
        <p>
            <a href="/service-manager/index">Simple, grab all</a><br />
        </p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('2) Adapter') ?></h2>
        <p>
            <a href="/adapter/local-adapter">Create Adapter Manually</a><br />
            <a href="/adapter/service-adapter">Grab DB Adapter from service locator</a><br />
            <a href="/adapter/simple-query">Simple query using the service adapter</a><br />
        </p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('3) Select') ?></h2>
        <p>
            <a href="/sql-select-statement/select">Select Object</a><br />
            <a href="/sql-select-statement/where">Select Object w/Where</a><br />
            <a href="/sql-select-statement/join">Select Object w/Join</a><br />
            <a href="/sql-select-statement/joinLeft">Select Object w/JoinLeft</a><br />
        </p>
    </div>
</div>

<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('4) SQL Commands') ?></h2>
        <p>
            <a href="/sql-command-statement/insert">Insert Objects</a><br />
            <a href="/sql-command-statement/update">Update Objects</a><br />
            <a href="/sql-command-statement/delete">Delete Objects</a><br />
        </p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('5) Table Gateway') ?></h2>
        <p>
            <a href="/table-gateway/select">Select from Gateway</a><br />
        </p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('6) Row Gateway') ?></h2>
        <p>
            <a href="/row-gateway/update">Update Row</a><br />
            <a href="/row-gateway/delete">Delete Row</a><br />
        </p>
    </div>
</div>

<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('7) Cool DB Things') ?></h2>
        <p>
            <a href="/cool-stuff/sql-string">Echo SQL Strings</a><br />
        </p>
    </div>

    <div class="span4">
    </div>

    <div class="span4">
    </div>
</div>